[build]
  command = "npm install --platform=linux --arch=x64 sharp && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NPM_USE_PRODUCTION = "false"

